import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./loginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./logoutBtn";
import DarkMode from "./DarkMode";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log(session)

  let res = cookies().get('mode')
  console.log(res.value)

  return (
    <html lang="en">
      <body className={
        res != undefined && res.value == 'dark' ? "dark-mode" : ""
      }>
        <div className="navbar"> 
          <Link href="/" className="logo">Appleforum</Link> 
          <Link href="/list">List</Link> 
          {
            session ? <span className="user-name">{session.user.name}
                        <LogoutBtn className="logout-btn"/>
                      </span> 
                    : <LoginBtn className="login-btn"/>
          }
          <DarkMode />
        </div>  
        {children}
      </body>
    </html>
  );
}